### ISSUE TITLE
Smarters 

### ISSUE THREAD

**Issue by gazza35** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#100]
Can you turn subtitles off permanently. Or just turn off as and when

**Comment by randheerNST** [comment]
Hi @gazza35 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
