### ISSUE TITLE
Please do not show empty categories

### ISSUE THREAD

**Issue by tomtruitt** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#102]
I have Customers without international on their lines who have 30+ empty categories in their playlist. Can you only display categories for Channels in the Bouquets on that person's line instead of showing all categories in the service?

**Comment by randheerNST** [comment]
Hi @tomtruitt ,

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
