### ISSUE TITLE
Newest Version 1.5

### ISSUE THREAD

**Issue by IAMDDS** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#103]
-On a Firestick the S in recordings is underneath but on an Android box it is normal.
-Show Full EPG allows you to continuously scroll to the right - Only problem is EPG doesn’t move.
-Show Full EPG off only scrolls to the right about 3 hrs before dropping down to next program in the EPG.
-Recordings only works in Live TV.
-On Demand has to be adjusted to best fit to be the correct Aspect Ratio of original Movie -Otherwise the movie is stretched vertically or Fattened horizontally and fills the screen)

**Comment by randheerNST** [comment]
Hi @IAMDDS 
Sorry for late reply

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
