### ISSUE TITLE
New version problems

### ISSUE THREAD

**Issue by Fryingpan77** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#106]
Hi. The record function doesn't work on the firestick 2 or the Nvidia shield. Firestick records for a minute then stops. Shield doesn't record anything.
TV guide still temperamental on firestick especially. Didn't download, then sometimes does. Was hoping for a download prompt when using the live TV tab like on phones.
Subtitles still on by default, and has a counter or chapter 1 at the bottom of the screen on some content in movies and TV series. On the shield, you can't even navigate down to turn them off.
The TV guide and subtitles are the biggest problem but the app it excellent. 
Thank you

**Comment by randheerNST** [comment]
Hi @Fryingpan77 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
