### ISSUE TITLE
DTS, DD...

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#107]
No passtrough for movies/series for encoded audio like DD, DTS...Everything is in stereo... That does not make any sense for most users... Not even channels that are in DD 5.1 are sent that way... They are also only stereo.

Please add option for audio passtrough.

**Comment by randheerNST** [comment]
Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
