### ISSUE TITLE
IPTV Smarters Box Edition

### ISSUE THREAD

**Issue by NIGHTSHADE-IPTV** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#109]
Hello,

Portuguese translation is very innaccurate! Can it be fixed? It's just a few words that really need to be corrected. If not possible better to remove it entirely...

I am very interested in buying app for my service and give it to customers but only if translation is correct or English only...

Best regards

John Nightshade

nightshade.iptv@gmail.com

**Comment by randheerNST** [comment]
Hi @NIGHTSHADE-IPTV 
Sorry for late reply and Thanks for your feedback

For updtaion in strings  or customizing your app you can mail us at our mail address written here
help@whmcssmarters.com

Thanks
