### ISSUE TITLE
Video codec h265 don't work

### ISSUE THREAD

**Issue by giovio** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#112]
In my Android TV Tcl C70 the channel in h265 don't work but the sound yes

**Comment by whmcs-smarters** [comment]
Hi, Sorry for that delay, we are getting the new version released very soon with many issues fixed. 

For the time you can use the external player. Long press on the running channel and play with external player.

Thanks

**Comment by randheerNST** [comment]
Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks

**Comment by jrviictor** [comment]
still the problem but in cell phone version,
