### ISSUE TITLE
iOS update 

### ISSUE THREAD

**Issue by shopshep** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#113]
On login in screen it gives mevan error when I put a name in the ANY NAME area of the log in page. 

I tested it on my phone after I did the app update and it give me request failed: not found (404) error. 
I tried my iPad with older version of app worked fine with channels and watching. Once I upgraded the app on iPad gives me the same error my phone gives me now. 

I tried uninstalling the app and reinstalling. Same error. I also checked my account info and it is correct. I'm using iphoneX and iPad Pro 9.7 iphoneX has apples latest operating system and iPad on older version.

**Comment by whmcs-smarters** [comment]
Hi @shopshep We have fixed that issue. Please test our Latest version from the APP Store. 
Thanks
