### ISSUE TITLE
STAY AWAY from this App unless you get it for free

### ISSUE THREAD

**Issue by IAMDDS** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#114]
I signed up for this app back in April when it was first announced, and over the releases it has not gotten any better. They fix 1 issue and then create 2 more. It still takes forever to download the guide, Guide still does not work correctly, Latest release was all about recording - it doesn't work worth SH!t. They run the whole app through their server first so when their server goes down you can not access your IPTV provider.
They will take your money, They will over promise and under deliver. I am just saying BEWARE especially for $300 or $500 lifetime.

**Comment by whmcs-smarters** [comment]
Wow, I was waiting for you Man. Thank god you met me here. 


We have more than 5 dedicated servers with load balancers with this app. So far, we had no issue with the server down or something. 

In this way, your Xtream Codes panel is hosted on any server, if its down then ?

your website is hosted on the server if that goes down then?

Just grow up Man. we know how to handle such kind of person.

**Comment by IAMDDS** [comment]
You know how to handle what?
You still have not fixed guide issues from the very first demo I received and you Amanpreet promised you would fix it 4 versions later and it is still not fixed.
The guide still takes forever to load through your server, I can use another app and the guide loads pretty quickly.

I have witnessed twice where your server goes down and then we cannot access our IPTV panel/provider.
