### ISSUE TITLE
Looking to setup an IPTV server

### ISSUE THREAD

**Issue by DoubleZeroUK** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#116]
What do I need to setup an IPTV server do I just need to purchase the IPTV Smarters Pro app? Or do I need IPTV Panel Professional v2 as well? Do I need my own hosting account for cpanel? Thanks in advanced.

**Comment by whmcs-smarters** [comment]
Hello @DoubleZeroUK IPTV Smarters is just like  a player, you should have your own content
. 

if you need a custom version with your logo, app name and linking it your IPTV panel then we are offering the same. 

https://www.whmcssmarters.com/android-app-for-xtream-codes-iptv-smarters/

thanks
