### ISSUE TITLE
configurando um teste

### ISSUE THREAD

**Issue by rtecunseh** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#117]
estou configurando o aap para testar e esta dando erro code 404

**Comment by randheerNST** [comment]
Oi
Seus problemas podem ter sido corrigidos. Isso estará disponível em nosso próximo lançamento.

Por favor, verifique se você está usando um URL válido do servidor, como este exemplo de URL abaixo:

Corrigir URL do servidor: http: // yourdns: port (Não é necessário digitar / c ou qualquer outra coisa após o número da porta)
URLs de servidor inválido: http: // yourdns: port / c ou http: // yourdns: port / get.php etc

Espero que esteja claro agora.

Ainda assim você tem alguma dúvida, entre em contato conosco em:
mailto: help@whmcssmarters.com

obrigado
