### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#119]
It would be better if you could make automatization of channels, vod, epg and all other every 2 hours in background. Make it transparent for end user, so that he does not need to make manual update, and that he does not see that data are being updated.

**Comment by whmcs-smarters** [comment]
Hello, @azsenca Thanks for your feedback. we will be thinking about it but if we update the channels in the background. it will affect the app's running an app's performance. 

but still, we will be checking this out. thanks
