### ISSUE TITLE
Few bugs

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#120]
-App wont exit, double press back and it exits app and starts it immediately.
-EPG not updating when watching same channel long time. In info is show that was on channel start.
-When changing channel by pressing channel number on remote, sometimes channel icon stays from old channel and when you press channel up or down it does not go up or down from that channel, but from previous that was selected in list.
-Sometime EPG updates but it wont show, you have to force app exit and open it again to show EPG
-TV Guide menu wont scroll right with remote on tv box. It goes in new row.

Few recomendations:
-Enable deinterlacing filter
-Enable HQ Scalers for SD channels
-Enable antialasing filters

**Comment by randheerNST** [comment]
Hi azsenca,

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
