### ISSUE TITLE
Recording

### ISSUE THREAD

**Issue by iptvclub** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#121]
version 1.6.
When recording if you change channel you do not get a warning that the recording will stop.
A new feature was trailers in Movies and Series. I only see the trailer option in Movies, none in series.

**Comment by samdudu1** [comment]
recording using EPG would be a better solution. That way you can record and watch something else

**Comment by whmcs-smarters** [comment]
Yes. we are working on this feature. will be adding in the next release. Thanks for your feedback.
