### ISSUE TITLE
Issue - TV Box version 1.6

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#122]
1. Recording - EPG recording is better. Select a program that would play at a future date / time to record
2. OTA - over the air app update would be better, instead of having each client download new version of the app, when there is a new version, it prompts the user to download and install the latest version

**Comment by whmcs-smarters** [comment]
@samdudu1 Yes, we are already working on recording from the EPG page. 

Thanks for your feedback.
