### ISSUE TITLE
Issue on H.265 streams

### ISSUE THREAD

**Issue by adamo331** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#125]
please fix the issues on streams with codec h.265 video play with slow motion

**Comment by whmcs-smarters** [comment]
Hello @adamo331  Please use " HW " option to get it worked. 

while playing video, you can see the "HW " at the bottom that would fix this. 

It's hardware decoding feature of the native player allows you to play the video smoothly.  

Thanks
