### ISSUE TITLE
Poor Croatian translation

### ISSUE THREAD

**Issue by wragg** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#126]
Hi, I have found a few very irritating mistakes in Croatian translation. Is there a way to fix those? I would gladly fix them myself for free if you want.

**Comment by whmcs-smarters** [comment]
Hello @wragg could you please explain or share the right translation?

So, we can fix them accordingly. Thanks

**Comment by wragg** [comment]
Hi,

I can think of two translations right now. There are more, but these two are really bad translated:
"Osvjezavajuca aplikacija" should be "Osvjezavanje aplikacije"
"Zivjeti sa EPG" should be just "Pregled programa" or even better "TV raspored".
I don´t have the app right now in front of me so I can not tell you more.

**Comment by randheerNST** [comment]
Hello @wragg 
please share the your email, so that I can send you string file for translation.

Thanks
