### ISSUE TITLE
Movie seeking

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#130]
Movie seeking is very poor impleneted.

Make seek +5min and -5min. Everything under that does not make any sense for movies and series.
Also, you could map it to left and right arrows on remote, and even better add +/-10min on up and down arrow when watching movies or serie.

**Comment by jackchoui** [comment]
this is a must!!

**Comment by whmcs-smarters** [comment]
Hi @azsenca fixed that issue in our new upcoming version v2.0 You need to just hold that seek forward and rewind button for fast seeking.
