### ISSUE TITLE
Feature ideas

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#131]
When holding "back" button on remote, go to previosuly watched channel. That way you can fast switch between 2 channels.

When you start to watch channel, start recording of that cannel for time-shift function. That way you can rewind last 2 hours (example) watched, without need to go to TV archive, or even if TV archive is not enabled for that channel. Similar to pause function that starts to record when you pause live channel.

**Comment by whmcs-smarters** [comment]
Hi, @azsenca  Thanks for your suggestion.
