### ISSUE TITLE
Phillips android tv

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#132]
On some phillips android tv, video picture is really bad.
Don't know if phillips android os does not support some filters or something, but even HD channels are pixelated, grainy, have ghosting, color bending, etc...

And when the source is interlaced, you can see lines in every scene, fast scenes are unwatchable.

Youtube, netflix, amazon video all have perfect picture, so it is not related to tv settings or something else.

I have tested on another device in same time, and it is completly different.

And there is no DD/DTS audio on phillips android tv. Everything is 2.0 stereo, even if it is set to passtrough DTS/DD in tv settings.

**Comment by whmcs-smarters** [comment]
Hi @azsenca fixed that issue in our new upcoming version v2.0
