### ISSUE TITLE
Long time playback problem

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#133]
When you watch same channel for longer than 4 hours, on some devices playback becomes jerky, and starts to stutter. Then when you stop playback and start again, it is normal.

**Comment by randheerNST** [comment]
HI @azsenca 
Could you please specify the name of devices where are getting jerk in videos or please send the videos in attachment to help@whmcssmarters.com so that we can fix the bug

Thanks
