### ISSUE TITLE
Drop external players

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#134]
For me, and most users, external players are confusing and useless.

It you are making app for playing something, work on your player, make it versatile, dont just give up and put option to play it in another player.

VLC is most compatible player, work with them to make build for internal app player that will work perfectly. This way it is hard to give customer support if they use mx or external vlc player. They also update players, and sometimes new versions have troubles.

**Comment by randheerNST** [comment]
Hi @azsenca 
Actually this gives user more option to play with their selected players. Its very easy to use and change. If any of user don't want to use then no need to change the player. 
But we got request from client to make app with default player VLC or Mx, thats why we make option in such a way all can use the app easily. 
Our working is continues on player to make it more versatile. 
Thanks for giving valuable feedback and suggestion.
