### ISSUE TITLE
User agent

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#135]
Remove user agent option from app settings and transfer that option to admin pannel. That way admins can put specific user agent and allow or deny service, see statistics etc. Similar to change portal setting.
I have seen users putting in words like "fu*k you, a**hole, w*ore, su*k, etc..."

It is not nice, and for most casual users it is just confusing.

**Comment by dmtg** [comment]
But if isp provider block traffic this is a solution for the problem.

**Comment by azsenca** [comment]
ISPs does not block traffic by user-agent.

**Comment by whmcs-smarters** [comment]
Hi, @azsenca  If you want us to rebrand an APP for you then we can hide that User-agent feature.
