### ISSUE TITLE
REMOVE default launch on boot please

### ISSUE THREAD

**Issue by techker** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#137]
Hello can you remove the default launch on boot option please...every time i install it for a client need to login and remove the option......

**Comment by powerstreamtv** [comment]
I second this..

**Comment by whmcs-smarters** [comment]
Hi @techker  this is not an issue. You can simply uncheck that Auto Boot option from general settings.

**Comment by powerstreamtv** [comment]
It is an issue..  it shouldn't auto launch, it overrides other default settings from other apps.   It should be off from default and those that want it should turn it on.  It should be opt-in, not opt-out.

**Comment by mochoandre** [comment]
I third this
