### ISSUE TITLE
IPTV Smarters Pro - Favourites EPG not working

### ISSUE THREAD

**Issue by shezsharks** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#142]
It was all working fine and I set up my favourites in all categories but now there is no EPG in favourites and when I watch live tv in favourites it revers back to the home page - there is a glitch somewhere - can it be fixed ???
![20181019_151829](https://user-images.githubusercontent.com/44304351/47267662-e3b86000-d53e-11e8-9133-d8af0243e3be.jpg)

**Comment by Kamperfan** [comment]
Same problem! I just saved 53 channels to Favourites. The Favourites box shows 53 channels there but when I click on the Favourites box I keep getting returned to the Home screen.
Hope someone can help

**Comment by shezsharks** [comment]
I was given advice on this and it worked. Totally uninstall IPTV Smarters from your device and start from scratch reinstalling it with all your private info and then it worked fine, no issues since then.

**Comment by Kamperfan** [comment]
Thanks Susan,  I'll give it a go!

**Comment by whmcs-smarters** [comment]
Hi @shezsharks and @Kamperfan we have fixed that issue in our new upcoming version v2.0

**Comment by cabdixamiid** [comment]
Mdjej

**Comment by pc1969** [comment]
I just installed v1.3 to my Apple TV and the favorites are not showing up. I have also deleted and reinstalled. Please advise.
