### ISSUE TITLE
Delete unnavailable favourites

### ISSUE THREAD

**Issue by hugodslo** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#144]
It’s not possible to delete streams that became unavailable from the favourites. If someone remove a stream from the list it becomes only an icon on the favourites list and we can remove it.

**Comment by whmcs-smarters** [comment]
Hi @hugodslo  fixed that issue in our new upcoming version v2.0

**Comment by hugodslo** [comment]
Ty

**Comment by gosssmith** [comment]
Problem still exits in 2023.
