### ISSUE TITLE
Aspect ratio on VOD and live TV.

### ISSUE THREAD

**Issue by Fryingpan77** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#145]
The app is almost perfect however. Using the default player, when we set the movies to the correct aspect ratio. It now changes some live TV channels to have borders left and right, or in some cases, a small view in the middle of the screen. The previous default player didn't effect live TV at all. Can this be rectified?. Thanks in advance.

**Comment by whmcs-smarters** [comment]
Hi @Fryingpan77  fixed that issue in our new upcoming version v2.0
