### ISSUE TITLE
support to any media player

### ISSUE THREAD

**Issue by alessa26** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#147]
Hello.
would it be possible to add support to any media player and not just mx or vlc?
I use a box Android x96 mini and I find the player for default less than perfect player.
thank you.

**Comment by alessa26** [comment]
Up?

**Comment by whmcs-smarters** [comment]
Hi @alessa26  we have added that feature in our new upcoming version v2.0

**Comment by alessa26** [comment]
OK , is possible to have a beta version ?
________________________________
