### ISSUE TITLE
FAVOURITES list NOT working when there is more then 1 iptv service

### ISSUE THREAD

**Issue by bonbag10** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#148]
Hi, I have 2 iptv accounts using the latest version 1.6.9 or 1.7.5 smarters pro. 

Everytime I try setting up my channel list for favourites, save all my favourites for both iptv servers, I end up loosing majority of them, then when I attempt too go into favourites section the app itself crashes. 

THIS ONLY OCCURS WITH 2 IPTV ACCOUNTS SET-UP AT THE SAME TIME. Having just the one operating, no problems

**Comment by whmcs-smarters** [comment]
Hi @bonbag10  fixed that issue in our new upcoming version v2.0
