### ISSUE TITLE
Unable to play stream to windows Tablet

### ISSUE THREAD

**Issue by scubakev** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#149]
I have set up IPTV smarters the same as i have on my laptop downloaded VLC on my laptop everything runs fine but on my tablet i can see the menus but when i try to play a video i just get the loading circle and VLC dose not open in the background can someone offer any advice

**Comment by whmcs-smarters** [comment]
Hi @scubakev  you can choose any external player in our new upcoming version v2.0

**Comment by scubakev** [comment]
When is this available and where can I get the update thanks

Sent from my iPhone

On 6 Feb 2019, at 19:07, Amanpreet Singh <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #149<https://nam05.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fwhmcs-smarters%2FIPTV-Smarters-TV-Demo-APK%2Fissues%2F149&data=02%7C01%7C%7C0fecb2a1013f48026b7008d68c2bb67c%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636850516703125266&sdata=iRIQlZcixxJSt%2F3cbXL2bzkn40bEywri%2FLDGQ8ycElE%3D&reserved=0>.
