### ISSUE TITLE
trial/reseller info

### ISSUE THREAD

**Issue by ranger77dvb** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#151]
hello im interested in your iptv service. how do i get the trial info. also im very interested in becoming a reseller.    thank you steven

**Comment by NicoLiam** [comment]
Hi Steven. That was really nice and fun to hear. Please just send me your email, so I can send you some information for a trail account and log in for a re-seller account. Looking forward to hear from you again. Sorry, for this late reply, I will check messages more often. ✨👨‍🔧

**Comment by ranger77dvb** [comment]
Steve g
ranger77dvb@gmail.com

**Comment by ranger77dvb** [comment]
Hi this is Steve can you please send me the information on the trial and
resellers information ASAP thank you here's my email address.
ranger77dvb@gmail.com

**Comment by ranger77dvb** [comment]
hi this is Steven can I please have the information for a trial and also
I'd like to become a master reseller can you please get back to me ASAP
thank you I really appreciate it
