### ISSUE TITLE
Discontinued?

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#152]
No word from whmcs-smarters...
Is this discontinued?
So many little bugs:
-no subtitles on Native decoder
-DTS, DD works only on Native decoder, but then no subtitles...
-Resume video, start over buttons are switched
-Subtitles on many android boxes are very small al all the way to the bottom, on Android TV OS it works fine.

Anyone from whmcs-smarters read this??

Not any update for 3 months...

Talk about customer support and development...

Really disappointed....

**Comment by whmcs-smarters** [comment]
Hi @azsenca  These all the points are fixed in our upcoming release. v2.0
