### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#153]
- Make OTA updates directly from server, not over Google Play Store
- Implement Push notifications, or in-app notifications so we can send informations to clients directli to app screen (Like MAG/Stalker have messages)

**Comment by whmcs-smarters** [comment]
- Yes, we can provide that feature on the special requirement.
- Announcement feature is already available in our APP so that you can notify your client by sending an announcement from our client area.
