### ISSUE TITLE
Epg not downloading 

### ISSUE THREAD

**Issue by rchircop19** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#155]
Epg is giving me a network error. Channels work no problem but epg gives this error most of the time using the stalker system.

**Comment by whmcs-smarters** [comment]
@rchircop19 We have fixed this issue in our latest version 2.0. 

Thanks

**Comment by rchircop19** [comment]
It has not been fixed yet. The current app version is 1.7.9.7. When will version 2.0 be available please?
