### ISSUE TITLE
Poblem with EPG."Network error occurred. Please try again"

### ISSUE THREAD

**Issue by tomasz76** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#156]
Hello, I have installed the last version of the App  1.7.9.7. Everything works fine on my smartphone, but on the Android Box  I can't update my EPG and I get the message "Network error occurred , please try again"
What is the reason for this?

**Comment by whmcs-smarters** [comment]
Hi @tomasz76 Network Error issue is fixed in our Latest version v2.0.
