### ISSUE TITLE
How to get a free demo ?

### ISSUE THREAD

**Issue by harman-newspark** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#16]
We have noticed a few clients are getting  " Could not connect to Server"  or "Invalid login"  or Invalid request. 
they are not able to try our free demo. 

Please explain once again here properly how to get a running demo version for our IPTV Smarters - TV box

**Comment by whmcs-smarters** [comment]
Step by Step Instructions to get a free demo - IPTV Smarters - TV Box Version 

- Please place an order for a demo **[here](https://www.whmcssmarters.com/clients/cart.php?a=add&pid=122)**

- Enter the following details : 
       - Streamline Username 
       - Streamline Password 
       - Server URL / IP 
      - Server Portal 

Make sure you have entered the correct info. 

- Once you place the order, you will get an email with a link where you can download your APK
Or
- You can simply download the APK file from your Client Area -> Support -> Download 
Or 
- You can download your APK file here [Latest Demo APK file](https://www.whmcssmarters.com/clients/index.php?rp=/download/category/11/Android-App---IPTV-Smarters-.html)

**Comment by whmcs-smarters** [comment]
If you have already placeed an order and still getting "Could not connect" then please place an order a again with **new username** then it should work. 

Thanks

**Comment by brianskodi** [comment]
checked everything still not working, i cant see where you enter the username and password required by iptv supplier

**Comment by santiagoolivan** [comment]
Hello, I do not have an iptv server in production at this moment, to make the demo of the apk, you can provide me one for the demo.
regards

**Comment by whmcs-smarters** [comment]
@brianskodi today we have put there a button " Test My Details" that verify your entered details. 

so you can test your details for a demo then you are good to use our demo

**Comment by whmcs-smarters** [comment]
Hi to all, 

We have put a button there " Test My Details " that verify your details either it's correct for a demo or not. then you can proceed further. 

![demo-details](https://user-images.githubusercontent.com/28225708/39084810-17d15ffe-4598-11e8-9cee-199b49309473.png)

**Comment by miercoles1** [comment]
Add in setting option subtitles english french etc...  
Add in setting option language  english french etc....
Add in setting option format screen 4/3 16/9 etc...

**Comment by whmcs-smarters** [comment]
It's available on the Play Store : https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

**Comment by whmcs-smarters** [comment]
IPTV Smarters Pro v1.6 released but it's not available on the google store yet. 

You have to place an free order for this demo and test it

**Comment by randheerNST** [comment]
Hi @brianskodi , @santiagoolivan , @miercoles1 
Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Thanks

**Comment by jasioo12** [comment]
Please correct the following errors before continuing:

Streamline Username is required
Streamline Password is required
IPTV Server Port is required       What to enter.

**Comment by cyoung121069** [comment]
Will it not accept bit.ly url?

**Comment by fradducho** [comment]
Hi, I have a doubt.

I have a xtreamcode service installed locally in my house.

when i try to put the ip server and port it tells me invalid url.
I do not know what to do.


I have to pay IPtvSmarters so I can include my ip? in your list and that your application can work? Is this how it works? or do I have to have some special port open?

**Comment by brianskodi** [comment]
For Setup guides use the free Telegram App, see below.


Telegram is a free app for Android, Windows, IOS or Amazon device, available from app store/playstore. Once you have it, the link to the channel is below.

https://t.me/joinchat/AAAAAFgdG80e1suFZfwzEA 






Sent from Yahoo Mail on Android 
 
  On Wed, 5 Jun 2019 at 18:02, Fraddy Gil<notifications@github.com> wrote:   
Hi, I have a doubt.

I have a xtreamcode service installed locally in my house.

when i try to put the ip server and port it tells me invalid url.
I do not know what to do.

I have to pay IPtvSmarters so I can include my ip? in your list and that your application can work? Is this how it works? or do I have to have some special port open?

**Comment by Aymen53** [comment]
🔴🔴 Meilleur IPTV 📺 12 mois Confiance et garantie ✅  voulez essayer le test Atlas Pro, QHDTV, Volka, Neo, iron pro.., ou tout autre serveurs WtsApp: +213655135904
