### ISSUE TITLE
Header/ footer doesn't disappear when video playing

### ISSUE THREAD

**Issue by whmcs-smarters** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#2]
I have also noticed that when you select LIVE TV from the Main screen, then select your category and then select your channel, the banner stays on the bottom of the screen and does not disappear.

**Comment by harman-newspark** [comment]
Resolved - Demo Version 1.1

**Comment by whmcs-smarters** [comment]
it works when we play the big screen the first time then it goes disappeared but when you press "OK" again it will show the header/footer ( channel name and EPG info with play, pause button) but it doesn't disappear again.

**Comment by whmcs-smarters** [comment]
Fixed - Demo Version 1.2
