### ISSUE TITLE
Not responsive for difference resolution

### ISSUE THREAD

**Issue by kurddata2006** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#20]
Hi , first thanks for greate app .  as screenshot shown the app is not responsive for different screen resolutions .

https://www.dropbox.com/s/e1aek3yv970bvts/Photo%20Apr%2020%2C%2017%2028%2049.jpg?dl=0

**Comment by whmcs-smarters** [comment]
Fixed it in Demo Version 1.2
