### ISSUE TITLE
Full screen

### ISSUE THREAD

**Issue by miercoles1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#21]
you can remove the blue horizontal bar on the screen

**Comment by miercoles1** [comment]
Bug : when I select a channel in full screen remains a blue bar

**Comment by whmcs-smarters** [comment]
@miercoles1 Could you please share your screenshot? 

I can't see any blue screen.

**Comment by miercoles1** [comment]
Le sam. 21 avr. 2018 à 07:43, Amanpreet Singh <notifications@github.com> a
écrit :

**Comment by miercoles1** [comment]
Lorsque je sélectionne une chaine en pleine écran reste un bandeau bleu

**Comment by whmcs-smarters** [comment]
Already fixed and should be Ok with Demo version 1.2 and Paid Version as well 

Duplicate issue #2
