### ISSUE TITLE
VOD crashes

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#22]
App crashes when you play any video that has posters. All video that does not have posters work fine

**Comment by whmcs-smarters** [comment]
Thanks for your feedback, We will fix it first as it's crash. 

@harman-newspark Please check this out and fix it asap

**Comment by whmcs-smarters** [comment]
@samdudu1 , could you please share your username only?

We are not able to replicate this issue. it's working fine for me

thanks

**Comment by whmcs-smarters** [comment]
We were not able to replicate this issue. 
Feel free to reopen this issue but don't forget to share your username and a quick video. Thanks

**Comment by rock2011** [comment]
I am getting this same issue. Was working fine but suddenly anything on VOD with a poster immediately crashes IPTV Smarters
