### ISSUE TITLE
Bug - menu bar

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#23]
Live TV > Click on any category > click on any channel > channel plays > click again to make it full screen.
As soon as it's full screen "menu bar" at the bottom of the screen does not go away

rewind | pause | fast forward - bar does not go away
![menubar](https://user-images.githubusercontent.com/35354721/39066702-2f3867ba-4493-11e8-8c87-78ed88178d86.jpg)

**Comment by whmcs-smarters** [comment]
It's a duplicate issue, already being addressed:  #2
