### ISSUE TITLE
Issue in TV

### ISSUE THREAD

**Issue by nishal-newspark** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#26]
The clock does not change time in the EPG after you open it and while looking through channels.

The clock in the Live TV does not change time after you open it.

Banner disappears now after selecting channel in the LIVE TV mode but if you hit select again the banner pops up and does not disappear - unless you hit the back button or play/pause????

**Comment by whmcs-smarters** [comment]
Fixed - Demo Version 1.2
