### ISSUE TITLE
Subtitles not working

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#27]
I have on all my VODs subtitles in MKV container. Player does not load them. Please make to autoload subtitles if any, or add option to load subtitles in player OSD or in Settings menu.

Also add option for audio passthrough in setting. I have FHD VOD with DTS/AC3 master audio for extreme clients that require audio passthrough...

**Comment by whmcs-smarters** [comment]
Done - Version 1.4
