### ISSUE TITLE
Pincode - suggestion

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#28]
It is not user friendly to use "Username" and "Password" - it is not easy to type uppercase and lower cases or symbols on any STB. It is easier to enter numbers 0,1,2,3,4,4,5,6,8,9 
Do you have the feature to use numbers?

**Comment by whmcs-smarters** [comment]
you can keep username and password like 0,1,2,3,4,4,5,6,8,9 then it will allow you to login accordingly.
