### ISSUE TITLE
The channel listing in the guide is not stable

### ISSUE THREAD

**Issue by wendellbalous** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#3]
In the EPG, the orange time line does not stay in view as the user goes down the channels. Depending on the length of the show that is highlighted, the time will move hours ahead or behind, hiding the timeline from view. This confuses the user because it does not accurately inform the user of what is currently on based on the timeline. 

This feature does not function like a normal EPG guide.

**Comment by whmcs-smarters** [comment]
You mean if we are on Live TV and scroll down to the next channel then EPG info stays stable, it doesn't change according to next channel that we scroll down?
If I am right, then we are already done that you can see in our next Demo 1.2 version or Paid Version. 

When a user goes down, the EPG info under the channel should be changed in our next version. (1.2 or Paid) 

if still, we have not got you then please share a quick video, we will be doing according. Thanks

**Comment by GIPTV** [comment]
Hello.
I believe this user is talking about the same thing I came to report. I have attached a video. The EPG goes crazy as you scroll down if it is a long show. It makes it very difficult to use the EPG view.
Video - https://streamable.com/evpa0

**Comment by IAMDDS** [comment]
The timeline jumps all over after it encounters a long program, While scrolling down the EPG It needs to follow the timeline, Great Video GIPTV

**Comment by whmcs-smarters** [comment]
yes, it's fixed in Demo Version 1.3.1 - thanks
