### ISSUE TITLE
Auto-Start  on boot

### ISSUE THREAD

**Issue by whmcs-smarters** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#31]
1. Ability to set the app as a system launcher (if you decided to deploy a TV box as retail with it as system app / launcher) 

add other option to make the apps run automatically when the box start

**Comment by azsenca** [comment]
It would also be great if you could make flash image for amlogic boxes (S905X, S905W, S912...)

Something like libreelec which is based on JeOS linux and runs only Kodi.

That way we can make complete branding of the box and make sure users will use only our service with our box.

Think that should not be hard to make, but if you make this... I do not have words...

**Comment by whmcs-smarters** [comment]
Yes. it's done in v1.4 Version

**Comment by Xat59** [comment]
In my case, I need to disable the auto start. Please I am not able to configure it.

**Comment by Nico83500** [comment]
Hi, same here. I'm using the free version and I can't change settings to disable autostart. Thanks.

**Comment by conroyke56** [comment]
Need to be able to disable this feature. Or gonna have to use another app.

**Comment by nielsch87** [comment]
In my case also dont want to auto start on boot, please make it configuarable.

**Comment by m-combinator** [comment]
Same here, having the app autostart by default is annoying and I don't see any option to disable it.

**Comment by nielsch87** [comment]
I just the premium version and could desable it from settings :)
