### ISSUE TITLE
Channels dont works in v1.2

### ISSUE THREAD

**Issue by kurddata2006** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#33]
1-after updating to v 1.2 , the live channels can not and  pop up Reconnecting ...   again and again .
user stream : rokutest
2-I have test with another  username and password (try to change account) but  could not and write can not connect to server.
3- GUI responsive is same as before was (is not responsive with different resolution )
Thanks

**Comment by whmcs-smarters** [comment]
1-after updating to v 1.2, the live channels can not and pop up Reconnecting ... again and again.
user stream: rokutest= **I have checked your details, the working streams are working. you have many streams that are not working on the backend.** 

![rokutest](https://user-images.githubusercontent.com/28225708/39108318-3f2d0a6e-46e5-11e8-9dd4-a29b948c9ac9.jpeg)

2-I have tested with another username and password (try to change account) but could not and write cannot connect to the server.= **Sorry for that Our demo was not creating correct between 22 Apr - 23 Apr. I have fixed your demo and also, my team fixing another demo as well.** 

now, Anyone can get the demo working now. we have resolved the issue. 

3- GUI responsive is same as before was (is not responsive with different resolution )= Should be fixed we have tested on an emulator with the same resolution. but will be checking it again.

**Comment by kurddata2006** [comment]
Hi , I have  create new account (in your website ) and create new  line stream . completely as new  user  and  download  the  demo apk . It could not login  with correct  username and password , return network error (I check connection , The device connected ).

Scrnsht :  https://www.dropbox.com/s/8ruhx2ym087ddm6/IMG_2041.JPG?dl=0

**Comment by whmcs-smarters** [comment]
your details not working. 

what version you are using for X.C ?

**Comment by whmcs-smarters** [comment]
Try now, it should be working, you have entered two times same username and the first time you have entered incorrect URL. that is not acceptable in our demo. I have fixed and able to log in now. thanks
