### ISSUE TITLE
Bouquet does not read in correct order

### ISSUE THREAD

**Issue by lookitsaaron** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#34]
APK does not read the bouquet correctly from Xtreme codes. The channels are reverse order.

Example

Xtreme Codes Boquet says
channel 1
channel 2
channel 3

APK reads in live tv and epg
channel 3
channel 2
channel 1

**Comment by whmcs-smarters** [comment]
Hi, we have a sorting option on the top if you want to change the order. 

We will be checking the default sorting order too. thanks for your feedback.

**Comment by lookitsaaron** [comment]
Where is the sorting option? I can't seen to find it.
