### ISSUE TITLE
EPG Not working

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#35]
I click on EPG, you cannot scroll up or down, just stuck on the 1st page that opens

**Comment by whmcs-smarters** [comment]
Hello @samdudu1 I checked its working for us, seems a data-specific issue, 

could you please share your ** App Username** Only?I will check your details and update you.

**Comment by samdudu1** [comment]
After rebooting the box it started working fine.
