### ISSUE TITLE
Enhancement & New Suggestions

### ISSUE THREAD

**Issue by whmcs-smarters** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#36]
i can say is wow it seems to be working great. The issues that i see.
1. the epg jumps around needs some work.
2. needs the ability to rearrange the groups
3. ability to add more than one sub i have 2 subs and would love the ability to add a back up sub to it.

but it works great easy to maneuver. 
i personally think this is just as good as gearstv mayfair guide.
simple and easy to use .

Looking forward to testing this even more. Thanks

**Comment by randheerNST** [comment]
Hi @stefanorickeets 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
