### ISSUE TITLE
Aspect Ratio Saving

### ISSUE THREAD

**Issue by whmcs-smarters** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#37]
can you please explain how we can set playback to display 16:9 as the default setting? I have to change ratio each time I change channels. This is a pain.

We have to save the currently selected ration so the user no need to change it again and again when they watch the video next time.

**Comment by josetohom** [comment]
I have the same problem with aspect ratio, 16:9 by default.

**Comment by whmcs-smarters** [comment]
Fixed in the Version1.4
