### ISSUE TITLE
Playback Ratio Setting

### ISSUE THREAD

**Issue by BlacDrill** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#38]
Good afternoon. There is a feature which is definitely need in this app. Can you please explain how we can set playback to display 16:9 as the default setting? I have to change ratio each time I change channels. This is a pain. From what I've seen this is not currently available in the app. Would you please incorporate this so the user can set a default playback ratio. Thanks in advance.

**Comment by whmcs-smarters** [comment]
Yes, we have started working on it. thanks

we will save the value of aspect ratio until you uninstall the app. thanks

**Comment by whmcs-smarters** [comment]
Fixed Demo Version : 1.3.1
