### ISSUE TITLE
whmcs-smarters/IPTV-Smarters-TV-Demo-APK 

### ISSUE THREAD

**Issue by vtcruz23** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#40]
whmcs-smarters/IPTV-Smarters-TV-Demo-APK 

Hey, 

The app is great! I am wondering when this will be fully accessible.

**Comment by whmcs-smarters** [comment]
It's available but it's for IPTV Provider, if you are using Xtream Codes then you can buy the paid version for your customers. Thanks
