### ISSUE TITLE
Live TV and EPG Picture in Picture 

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#44]
When scrolling down the EPG changes but the picture in picture remains the same. It would be better if when scrolling down and you stop on a channel before clicking "okay" to select and watch the channel, the small view area shows what is play on that channel

**Comment by whmcs-smarters** [comment]
Fixed - 1.4 Version

**Comment by samdudu1** [comment]
It would be better if you put a download link for the latest apk here. Going through your website is not straight forward. It's better if they is a place to download the apk
