### ISSUE TITLE
On Demand and Series - Bug

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#45]
All Video are not automatically sorted by Default "Top Added" showing the oldest on 1st. This is a big issue when you want to watch "Series" because the last episode is arranged 1st and the 1st episode is arranged or displayed last.
For example:
episode 1 - ABC
episode 18 - CYY

CYY is top on the list and displayed 1st and ABC which you should watch 1st is displayed last. 
And there is not "Top Added" like in the old app, the best thing is by default all VOD and Series should by arranged and display "Top Added". I don't know why you even have all the options / sort according to A-Z and Z-A. Everyone want to see the newest video at the top.

**Comment by GIPTV** [comment]
I would like to add to this that if you set the movies & series to 'Top Added'  it also affects the order of your live TV channels and changes your bouquets to displaying the latest added channels at the top. 

Please fix it so the movies/series sorting is 'Top Added' by default and setting it to that does not change the live tv sorting and leaves it at default.

Regards,

**Comment by randheerNST** [comment]
HI @samdudu1 , @GIPTV 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
