### ISSUE TITLE
EPG - Does not auto update

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#47]
Every morning when i open the app shows that the channels and vod refreshing, but the EPG does not, 
When i click on EPG shows nothing, i have to manually click to "refresh TV guide" every morning / day before EPG shows

**Comment by whmcs-smarters** [comment]
Hi, @samdudu1  that is the normal behavior. 

when you click on "EPG button"  after day tomorrow they will load the EPG. 

but we will do one thing we will load the EPG when it expires when you open the APP. Thanks

**Comment by rottedint** [comment]
so true

**Comment by Fryingpan77** [comment]
This is the main problem as far as I can see. The automation of the EPG update, doesn't always work. I'd be happy if it auto updated the channel lists and EPG on every start up. Great work though

**Comment by whmcs-smarters** [comment]
Fixed - 1.4 
EPG would be updated automatically when it expires
