### ISSUE TITLE
EPG Listings Cut Off

### ISSUE THREAD

**Issue by wendellbalous** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#49]
The newest fix to the EPG cuts off the listings before the timeline. This leaves gaps in the listings where the user can see the background of the app. The previous version did not have this.

The problem seems to be that the EPG active focus is on the show listings. When you move up and down, the focus cycles through the show listings. Since not all show listings are the same size (time length), the focus moves around based on the listing size. 

Suggestion: I believe that it would be a better user experience if the up and down active focus was on the actual channel name on the left (ex. US: Cinemax I), similar to the focus on the live TV section. The user could still move left and right to view previous and future show listings but up and down would only cycle through the channel names on the left.

I believe that this would greatly resolve your EPG user experience issue.  

![screenshot_20180501-084730](https://user-images.githubusercontent.com/421002/39475749-16ef6520-4d1f-11e8-8c55-19cce8bfd050.png)

**Comment by whmcs-smarters** [comment]
Ok thanks for sharing it , we will plan this fixes in our next version

**Comment by whmcs-smarters** [comment]
Could you please if it's fixed in our version 1.4
