### ISSUE TITLE
Con usar la demo 

### ISSUE THREAD

**Issue by cristian213689** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#56]
Hola  quiero usar la de.o de la app para comprar  y al colocar mi puerto y clave no me lo acepta que sera

**Comment by cristian213689** [comment]
http://kimbogrupol.us:8000

Ese es el puerto

**Comment by whmcs-smarters** [comment]
Make sure you are using Xtream Codes version 2.x or above. 

Secondly, please send us  a working streamline at help@whmcssmarters.com

thanks

**Comment by whmcs-smarters** [comment]
We will create a working demo for you and update you.
