### ISSUE TITLE
Please allow 2 or more accounts to run at the same time without login out

### ISSUE THREAD

**Issue by AZBoxEmperador** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#57]
I live in latin America and, no one will include our locals channels ever other than our own local IPTV providers, so can the option to have 2 or more accounts be added?... this was suggested to me from a local guy who is a disabled person with movement limitation and there is no option for his nvidia shield to have this working for him.

Thanks.

**Comment by randheerNST** [comment]
Hi @AZBoxEmperador 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
