### ISSUE TITLE
auto-update app 

### ISSUE THREAD

**Issue by whmcs-smarters** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#58]
auto update feature built into the app

**Comment by izzyv** [comment]
Can i get a demo

**Comment by izzyv** [comment]
For multiple url for the app

**Comment by Fryingpan77** [comment]
This would be a great feature to cover all devices that haven't access to the Google store.

**Comment by whmcs-smarters** [comment]
Fixed 1.4 Version
