### ISSUE TITLE
epg issue

### ISSUE THREAD

**Issue by rottedint** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#59]
epg problem is not fixed. you can only scroll to the time displayed on the screen. there need to be a continuous scrolling plus there should be a auto feature that you see whats on at the correct time on the left of the screen

**Comment by whmcs-smarters** [comment]
To Fix the scrolling issue we have it adjusted but we will add the option if you want to see the future program that are not visible in the current screen timing.

**Comment by rottedint** [comment]
That will be best

**Comment by whmcs-smarters** [comment]
Hi @rottedint We have fixed that issue in our upcoming release v2.0. Thanks
