### ISSUE TITLE
add play button too. so it play from the first episode

### ISSUE THREAD

**Issue by whmcs-smarters** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#60]
Hello
We have added our tv shows to the TV Series section on the panel. However, it appears it is not possible to see any individual episode synopsis. This makes no sense what so ever
Can you please advise of a fix or future update to include this ?

When you select a tv series, you can see the basic show synopsis, but when you select any particular episode of that show, it just plays without giving the show synopsis. It should go to synopsis page, where the play function is then available.

thanks

**Comment by whmcs-smarters** [comment]
Show description of each episodes as we are doing with series.

**Comment by randheerNST** [comment]
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
