### ISSUE TITLE
how to create password and username

### ISSUE THREAD

**Issue by johnlamah** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#62]
hello 
i have a working line, but my question is that, where can we get username and password. do we have to create our own password and username or only our service provider have to give us them . and what is server port in Nvidia AND IPTV Server URL/IP
finally and how to Create a streamline  Xtream Codes Panel 
YOUR HELP IS MUCH APPRECIATED

Regard
layee

**Comment by whmcs-smarters** [comment]
You have to create a streamline when you create a streamline you have to enter the username/password or it auto-generated then that username/password you can use into our app. 

but before it, you must place a demo order and registered your portal URL ( server url or dns) 

Order a demo : https://www.whmcssmarters.com/clients/cart.php?gid=24

**Comment by johnlamah** [comment]
So what is iptv server url/ip

And what's iptv server port. Those are very confusing
