### ISSUE TITLE
Users cannot Log in to app over the last couple of days!

### ISSUE THREAD

**Issue by limitless-hosting** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#68]
Hello

Users can not log in, this has been happening the last few days.

**Comment by limitless-hosting** [comment]
they were working fine, untill a couple of days ago, we have checked there subs etc, but now can not login

**Comment by Siriusblack1979** [comment]
I Can vouch for that i signed out to test for him and cant get back in, so i uninstalled the app , reinstalled it and still no joy , This APP is the dogs bollocks really good until update 

hopefully will be fixed soon 

Thanks ;)

**Comment by limitless-hosting** [comment]
all fixed by devs, thanks guys!
