### ISSUE TITLE
Demo Version 1.4

### ISSUE THREAD

**Issue by bkackdollar** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#69]
I've noticed that the Guide has a few bugs. 

- Can't select channel when there is no guide. Some category selections have more issues than others with this problem. (E.g. The UK category has loads of blank guide spaces)
- Video player doesn't play any channels, just has loading circle.
- Live Tv EPG doesn't load automatically. You have to load the EPG guide first and then revert back to Live Tv in order for the guide to show.

**Comment by whmcs-smarters** [comment]
Hello @bkackdollar could you please send your username/password at help@whmcssmarters.com?

then I will review and update you here. Thanks

**Comment by bkackdollar** [comment]
Username: newsmartline
Password: nS9UuST0zL

**Comment by bkackdollar** [comment]
?

**Comment by bkackdollar** [comment]
Any updates?

**Comment by bkackdollar** [comment]
@whmcs-smarters

**Comment by randheerNST** [comment]
Hello @bkackdollar 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
