### ISSUE TITLE
Since update to v1.4 audio and video out of sync

### ISSUE THREAD

**Issue by stefanorickeets** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#71]
Good day. Since the new update I'm have a small issue with the audio and video just a little bit out of sync on certain devices such as Amazon Fire TV.

**Comment by johnlamah** [comment]
How to find a username and password to login

**Comment by randheerNST** [comment]
Hi @stefanorickeets 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks

**Comment by randheerNST** [comment]
Hi @johnlamah 
Sorry for late reply, Thanks for feedback.

You will need to enter your Username, Password and Server URL that is provided by your service provider. 
We are not offering any streams, playlists etc.
