### ISSUE TITLE
Tv Box 1.4 Chopy audio using default player

### ISSUE THREAD

**Issue by jorgeraidel** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#72]
Hello

I am testing my Tv BOx 1.4 today and all my content with double audio , it sounds choppy using default player :(, works if you use external player like VLC player

**Comment by randheerNST** [comment]
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
