### ISSUE TITLE
EPG issue

### ISSUE THREAD

**Issue by luckytv** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#73]
On v1.1 when on the live tv section the epg used to pop up right away.  Now in v1.2 when scrolling through the channels you have to wait for the epg to load about a second on each channel.  I liked it better on v1.1

**Comment by stefanorickeets** [comment]
Also, when playing a stream the NOW and NEXT doesn't update.

**Comment by randheerNST** [comment]
Hi @stefanorickeets 
Sorry for late reply and Thanks for feedback. 

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
