### ISSUE TITLE
h265 does not run in app version 1.4

### ISSUE THREAD

**Issue by Jeffersoncharlles** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#74]
h265 does not run in app version 1.4

only in mx player as can be seen in the video
https://www.dropbox.com/s/12zqhcfzrlxyuno/092cc655-54a2-48b8-bb3c-1d7b26286293.mp4?dl=0
prediction to correct this problem?

**Comment by whmcs-smarters** [comment]
Hi @Jeffersoncharlles 

I have just played the h265 and it worked perfectly: https://drive.google.com/file/d/16LBbszkxHsLrnJQUkEUNqjnCpRut4iyD/view?usp=sharing

Also, it depends upon your device too if it supports h265 or not. we don't' use any Software Decoding at this moment. 

Thanks
