### ISSUE TITLE
Movies and Series playback issues

### ISSUE THREAD

**Issue by Fryingpan77** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#76]
Hello. Using the default player, live TV works great, however, movies and series buffer every few seconds. Movies not as much. Only option is to manually choose VLC player. Would be great if we could set VLC as the default player without choosing it ever time. Great work though. Really enjoying the app

**Comment by Fryingpan77** [comment]
Quick update. Looks like the default player now is VLC 3.0.0.
VLC 3.0.3 plays movies and TV shows flawlessly

**Comment by whmcs-smarters** [comment]
It's fixed in v1.4.2 and confirmed by many clients 
You can kindly test it out as well : https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

**Comment by Fryingpan77** [comment]
Can confirm it as been fixed in the new version. Thanks for getting back
