### ISSUE TITLE
Font size

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#77]
Fonts should be bigger on EPG info in channel list and on playing channel, because on medium TV size ~30" it looks tiny.
![img1](https://user-images.githubusercontent.com/1789117/41001626-c4eefc2c-6911-11e8-8f1f-1248ee9f9e0b.jpeg)
![img2](https://user-images.githubusercontent.com/1789117/41001628-c50a6246-6911-11e8-9ff2-16c2b1fc6d67.jpeg)

**Comment by randheerNST** [comment]
HI @azsenca 
Sorry for late reply and Thanks for giving us feedback. 
We  have fixed this issue. This will be available in our next update above 1.6.9.  
Thanks
