### ISSUE TITLE
Tv Guide Issue

### ISSUE THREAD

**Issue by r33ms** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#80]
When you back out of a full screen channel and show the TV guide, the channel preview just plays the top channel in the category instead of the channel you were watching.

**Comment by randheerNST** [comment]
Hi @r33ms 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
