### ISSUE TITLE
EPG not auto updating in new version

### ISSUE THREAD

**Issue by Fryingpan77** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#81]
Have the app on Nvidia Shield and firestick 2 and the EPG data does not auto update.
Same thing happened on the previous version.
Ideally need the channels, movies and series to auto update along with the TV guide, rather than separate downloads.
Say by pressing any box it would update after 24 hours. Maybe even 20 hours to avoid shortened EPG data after a day.

**Comment by Fryingpan77** [comment]
Quick update on my side. The Nvidia shield, and my Galaxy s7 now ask if you want to update the EPG and works as it should. However, the firestick 2 still will not auto update either the EPG or VOD. This is on the latest version of your release

**Comment by whmcs-smarters** [comment]
Hi @Fryingpan77  We have fixed that issue in our upcoming release v2.0. Thanks
