### ISSUE TITLE
Subtitles on movies

### ISSUE THREAD

**Issue by Fryingpan77** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#82]
Hello. Find that the subtitles feature, which is a great addition, is set to on by default. This cause some files to have numbers or chapter 1,2,3 etc permanently at the bottom of the screen. Could they be set to off by default for us to turn on when needed. Thank you for your work.

**Comment by whmcs-smarters** [comment]
sure, we will add this option to settings so, you can turn it off / on. 

we will set by default - turned off.

**Comment by Fryingpan77** [comment]
Brilliant stuff. Thanks for getting back so quickly

**Comment by randheerNST** [comment]
Hi @Fryingpan77 
Sorry for late reply

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
