### ISSUE TITLE
Aspect ratio problems on movies

### ISSUE THREAD

**Issue by Fryingpan77** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#83]
Hi. The buffer has been fixed in the latest version, however I've come across another problem. Some films shot in 16.9 are stretched to full screen, (top and bottom). Manually changing the aspect ratio doesn't fix it either. Changing to another player like VLC 3.0.3 or MX player fixes the problem.

**Comment by randheerNST** [comment]
Hi @Fryingpan77 
Sorry for late reply, Thanks for feedback.

Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
