### ISSUE TITLE
TV Catchup or Archive  storing for more days

### ISSUE THREAD

**Issue by whmcs-smarters** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#84]
We have started working on it . now we will show the TV catch up more than 2 days .

according to your recording. if you have 14 days stored in your panel then it will show all them.

**Comment by randheerNST** [comment]
Please try out our latest version v1.6.9 
https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Your issues might have been fixed . Thanks
