### ISSUE TITLE
FUTURE UPDATES

### ISSUE THREAD

**Issue by samdudu1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#87]
When there is a new version or app update, it will automatically be sent and users will be prompted to update the application, so that we don't have to ask each user to download, install and update. Does not matter if the customer installed the app from the playstore or via an APK. They would get the latest version as soon as it's released. 

This would be a nice feature to add, within 2 months you have had 4 versions, you can imagine telling customers to download and update 4 times within 2 months

**Comment by Fryingpan77** [comment]
Another good way round it, would be to have the app on Aptoide TV store. That way they can update the APK or download it. Great for firesticks and boxes

**Comment by samdudu1** [comment]
It's a very simple solution to implement, it's better than having it on Aptoide. So many app have the feature. Would be a nice one to add
