### ISSUE TITLE
Few bugs on android box

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#89]
Channel name text too big and EPG info text could be little bigger with scrooling:
![img_20180613_155035](https://user-images.githubusercontent.com/1789117/41355807-a1846ad0-6f22-11e8-8383-87646e1ba767.jpg)

Poster aspect ratio is wrong on movie/serie info:
![img_20180613_155450](https://user-images.githubusercontent.com/1789117/41355852-b77b6b4a-6f22-11e8-86f5-8eb3e59dd9d7.jpg)

Main Menu could be better arranged. This way does not look so good. Maybe make 3 big icons and under them lined 3 smaller icons for EPG, ACCOUNT and ARCHIVE
Also, Date and Time text could be little bigger.
![img_20180613_155543](https://user-images.githubusercontent.com/1789117/41355928-dbdbf87e-6f22-11e8-897b-296c0997d615.jpg)

**Comment by whmcs-smarters** [comment]
that is our default design and it's improved a bit in our v1.6.9. 

thanks
