### ISSUE TITLE
Subtitles 

### ISSUE THREAD

**Issue by miercoles1** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#9]
In setting add active/disable subtitles More important Than format time

**Comment by miercoles1** [comment]
In serie why i have no found

**Comment by miercoles1** [comment]
Catch no working i have message error

**Comment by whmcs-smarters** [comment]
Hi @miercoles1 Please share your username only so, we can look into it why it's not showing series for you. 
Please share the same username that you were testing with.  ( Only Username)
thanks

**Comment by whmcs-smarters** [comment]
Catch no working I have message error= Please check out the latest demo where we have fixed the TV Catchup playing issue?

**Comment by miercoles1** [comment]
Username : geronimo2

Password : geronimo3

Le ven. 20 avr. 2018 à 10:29, Amanpreet Singh <notifications@github.com> a
écrit :

**Comment by whmcs-smarters** [comment]
Fixed in 1.4 version
