### ISSUE TITLE
User-agent

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#91]
Add option in client area to set user-agent for app. Or set permanent user-agent when producing app for customer. I have special rules for app users, they get special bouquets, but I need to make sure they are using app. This is the best way. It is easy to implement, VLC player has option to set custom user-agent.

**Comment by whmcs-smarters** [comment]
Yes. we have added this feature to our version 1.6.9 

https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

Thanks
