### ISSUE TITLE
New Demo error / network error / network error 404

### ISSUE THREAD

**Issue by Garrett-Hutton** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#94]
Hi support

I am trying to demo your fantastic new IPTV player using my Vader account details and URL http://vaders.tv

Please help  :)

Many thanks, Garrett

**Comment by Garrett-Hutton** [comment]
PLEASE help...

**Comment by whmcs-smarters** [comment]
It doesn't support Vader as they have changed their default API. 

but we are releasing the new version where you can upload the m3u file so it will start working again. Thanks
