### ISSUE TITLE
Audio option

### ISSUE THREAD

**Issue by azsenca** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#98]
Add DTS and Dolby Digital passtrough option. Lots of VOD files are with DTS or DD audio, so end users with home theater equipment needs this option. It would be best to add global option in settings with list which codecs to passtrough (DTS, DTS-HD, DTS-MA, DD, DD-TrueHD, DD-HD+...)

**Comment by whmcs-smarters** [comment]
@azsenca could you please try our latest version v1.6.9 it might have been resolved now. 

https://play.google.com/store/apps/details?id=com.nst.iptvsmarterstvbox

If you still haveing the same issue , feel free to reopen this issue. 

thanks
