### ISSUE TITLE
missing video when streams off or disabled or expired

### ISSUE THREAD

**Issue by adamo331** [whmcs-smarters/IPTV-Smarters-TV-Demo-APK#99]
Hi

as you know there option in Xtream-codes called video setting where we put our video when streams Not on Air or account expired or disabled, so clients can see what is happen when try to open streams, so it will be nice to add this feature in the app because now when account is expired or disabled clients can't be log in to app so better to allow login in case account disabled or expired but when he try to play streams the video will show what is the status of his account. i have video setting enabled in my panel for not on air and disabled line and expired.

**Comment by whmcs-smarters** [comment]
Hi @adamo331 Thanks for your suggestion.
